routes:
  - path: /auth/callback
    method: GET
    executor: AuthCallback
    security: public

  - path: /api/v1/auth/config
    method: GET
    executor: AuthConfig
    security: public

  - path: /api/v1/auth/renew
    method: POST
    executor: AuthRenew
    security: public

  - path: /api/v1/auth/me
    method: GET
    executor: AuthMe
    security: authenticated

  - path: /api/v1/auth/logout
    method: POST
    executor: AuthLogout
    security: public
